### ISSUE TITLE
CMake后打开无法编译？

### ISSUE THREAD

**Issue by MickeyJson** [pgyszhh/CPUTypeHelper#1]
环境：WINDOWS10
问题描述：导出的Project,在WIN10上打开某些头文件无法link到
疑问：是只能在linux下编译吗？

**Comment by pgyszhh** [comment]
Window和Linux不同，在Window上没有编译时需要的链接库，因此最好的方式是放到Linux上编译，搭建一个虚拟机很方便，坑也少很多，如果强行在Window上编译的话，就需要解决确实库之类的问题，相对来说花费的代价较大；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pgyszhh/CPUTypeHelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 下午3:01
收件人:&nbsp;"pgyszhh/CPUTypeHelper"<CPUTypeHelper@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[pgyszhh/CPUTypeHelper] CMake后打开无法编译？ (#1)





 
环境：WINDOWS10
 问题描述：导出的Project,在WIN10上打开某些头文件无法link到
 疑问：是只能在linux下编译吗？

**Comment by MickeyJson** [comment]
多谢，解惑。
目前windows环境搭建确实不太好适配
